global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'grpc-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.17.0.1:8081']  

  - job_name: 'rest-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.17.0.1:8080']  

